In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("construction.csv")
df

area  size   price  age
0    2000     3   50000    3
1    3000     4   60000    4
2    4000     5   70000    5
3    5000     6   80000    6
4    6000     7   90000    3
5    7000     8  100000    3
6    8000     9  110000    5
7    9000    10  120000    7
8   10000    11  130000    2
9   11000    12  140000    6
10  12000    13  150000    4

In [3]:
df.isna().sum()

area     0
size     0
price    0
age      0
dtype: int64

In [4]:
inputs=df.drop(['price'],axis=1)
inputs

area  size  age
0    2000     3    3
1    3000     4    4
2    4000     5    5
3    5000     6    6
4    6000     7    3
5    7000     8    3
6    8000     9    5
7    9000    10    7
8   10000    11    2
9   11000    12    6
10  12000    13    4

In [5]:
output=df['price']
output

0      50000
1      60000
2      70000
3      80000
4      90000
5     100000
6     110000
7     120000
8     130000
9     140000
10    150000
Name: price, dtype: int64

In [6]:
from sklearn.model_selection import train_test_split 
X_train,X_test,y_train,y_test= train_test_split(inputs,output,test_size=0.8)
from sklearn.linear_model import LinearRegression

In [7]:
reg=LinearRegression()
reg

LinearRegression()

In [8]:
reg.fit(X_train,y_train)

LinearRegression()

In [9]:
y_predict = reg.predict(X_test)
y_predict

array([ 60000.00749999, 149999.98500002, 109999.99000001, 139999.97750003,
       119999.97750003,  50000.01499998,  90000.00499999,  79999.99250001,
       100000.0025    ])

In [10]:
from sklearn.metrics import r2_score


y_predict = reg.predict(X_test)


linear_regression_score = r2_score(y_test, y_predict)
print("R^2 Score (Linear Regression):", linear_regression_score)


R^2 Score (Linear Regression): 0.9999999999998146


In [14]:
from sklearn.linear_model import Ridge


ridge_reg = Ridge(alpha=1.0)  
ridge_reg.fit(X_train, y_train)

y_predict_ridge = ridge_reg.predict(X_test)
y_predict_ridge

array([ 60000.00972221, 149999.98222225, 109999.98944446, 139999.97527781,
       119999.97638892,  50000.01777775,  90000.00555555,  79999.99361112,
       100000.0025    ])

In [15]:
from sklearn.metrics import r2_score
y_predict_ridge = ridge_reg.predict(X_test)
ridge_score = ridge_reg.score(X_test, y_test)
print("R^2 Score (Ridge Regression):", ridge_score)


R^2 Score (Ridge Regression): 0.9999999999997734


In [16]:
from sklearn.linear_model import Lasso


lasso_reg = Lasso(alpha=1.0)  
lasso_reg.fit(X_train, y_train)

y_predict_lasso = lasso_reg.predict(X_test)
y_predict_lasso

array([ 60000.00044444, 149999.99944444, 109999.99988889, 139999.99955556,
       119999.99977778,  50000.00055556,  90000.00011111,  80000.00022222,
       100000.        ])

In [17]:
from sklearn.metrics import r2_score
y_predict_lasso = lasso_reg.predict(X_test)
lasso_score = lasso_reg.score(X_test, y_test)
print("R^2 Score (Ridge Regression):", lasso_score)


R^2 Score (Ridge Regression): 0.9999999999999999
